[project]
name = "media-master-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "botty-framework>=0.0.3",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.1",
]


[tool.uv.sources]
botty-framework = { workspace = true }
